routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Use get ?lang=locale
Route::middleware(['locale'])->group(function () {
    Route::get('/', 'MainController@index')->name('home');
    Route::get('/articles', 'ArticleController@index')->name('articles');
    Route::get('/article','ArticleController@show')->name('article');
    Route::get('/contact', 'ContactController@index')->name('contacts');
    Route::get('/catalog/','CatalogController@index')->name('catalog');
    Route::get('/catalog/{country}','CatalogController@index')->name('catalog-country');
    Route::get('/realestate/{name}', 'RealEstateController@index')->name('realestate');
});

Route::post('/getcities','MainController@getCitiesByCountryId')->name('getcities');
Route::post('/getcategories','MainController@getCategoriesByTypeId')->name('getcategories');
Route::post('/feedback', 'MainController@feedback')->name('feedback');
Route::post('/review', 'ReviewController@review')->name('review');
Route::get('/setlang/{locale}', 'MainController@setLang')->name('setlang');
Route::get('/setcurrency/{currency}', 'MainController@setCurrency')->name('setcurrency');
Route::post('/realestate/viewed', 'RealEstateController@viewed')->name('realestateviewed');
Route::post('/catalog/setproductview','CatalogController@setProductView')->name('setproductview');
Route::post('/catalog/setfiltertoggle','CatalogController@setFilterToggle')->name('setfiltertoggle');
Route::post('/catalog/getproducts', 'CatalogController@getProducts')->name('getproducts');

Auth::routes();

// admin-lte
Route::prefix( '/admin' )->group( function () {

    Route::get('/admin-lte/{locale}', 'Admin\AdminController@setLang')->name('lang');
    Route::get( '/', 'Admin\AdminController@index' )->name('dashboard');
    Route::get('/chart', 'Admin\AdminController@getChartData' );

    Route::resource('/users','Admin\UserController');
    Route::resource('/countries','Admin\CountryController');
    Route::resource('/cities','Admin\CityController');
    Route::resource('/generalSettings','Admin\GeneralSettingController');
    Route::resource('/realEstates','Admin\RealEstateController');
    Route::post('/upload','Admin\RealEstateController@multipleUpload')->name('multipleUpload');
    Route::resource('/articles','Admin\ArticleController');
    Route::resource('/attributes','Admin\AttributeController');
    Route::resource('/attributeTypes','Admin\AttributeTypeController');
    Route::resource('/feedbacks','Admin\FeedbackController');
    Route::resource('/services','Admin\ServiceController');
    Route::resource('/categories','Admin\CategoryController');
    Route::resource('/agents','Admin\AgentController');
    Route::resource('/pages','Admin\PageController');
    Route::resource('/ga','Admin\GoogleAnalyticsController');
    Route::resource('/reviews','Admin\ReviewController');

    Route::get( '/import/glamourapartments', 'Admin\ImportGlamourapartmentsController@index')->name('import.glamourapartments');
    Route::get('/filemanager','Admin\FilemanagerController@index')->name('filemanager');
    Route::get('/filemanager/show','Admin\FilemanagerController@show')->name('show-filemanager');

    Route::post('/feedbacks/sendreaction','Admin\FeedbackController@sendReaction')->name('send_feedback_reaction');

    Route::post('/import/import_glamourapartments','Admin\ImportGlamourapartmentsController@import_glamourapartments')->name('import_glamourapartments');
    Route::post('/filemanager/upload','Admin\FilemanagerController@upload')->name('upload-items');
    Route::post('/filemanager/new','Admin\FilemanagerController@folder')->name('new-folder');
    Route::post('/filemanager/delete','Admin\FilemanagerController@delete')->name('delete-items');

    Route::get('/getAttributesByName','Admin\AttributeController@getAttributesByName')->name('getAttributesByName');
    Route::post('/getAttribute','Admin\AttributeController@getAttribute')->name('getAttribute');

    // Avatar
    Route::post('uploadAvatar', 'Admin\UserAvatarController@uploadAvatar')->name('uploadAvatar');
    Route::post('removeAvatar', 'Admin\UserAvatarController@removeAvatar')->name('removeAvatar');

    Route::get( '/profile', 'Admin\ProfileController@profileEdit' )->name('profile.edit');
    Route::put( '/profile', 'Admin\ProfileController@profileSave')->name('profile.save');



//    Route::get('/impersonate/{user_id}', 'Admin\ImpersonateController@impersonate')->name('impersonate');
//    Route::get('/impersonate.leave', 'Admin\DashboardController@impersonate_leave')->name('impersonate.leave');

//    Route::get( '/', 'Admin\DashboardController@index' )->name('dashboard');

});

Route::get('clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    return "Cache is cleared";
});

Route::get('{name}', 'PageController@index')->name('page');

app/Models/Article.php
<?php

namespace App\Models;

use Dimsav\Translatable\Translatable;

class Article extends TranslateModel
{
    use Translatable;

    protected $fillable = [
        'image',
        'image_big',
        'image_show',
        'published',
        'viewed',
        'date',
        'slug',
        'available_translation',
        'created_by',
        'modified_by',
    ];

    public $translatedAttributes = [
        'name',
        'description_short',
        'description',
        'meta_title',
        'meta_description',
        'meta_keyword',
    ];

    protected $with = ['translations'];

    public function getAuthor(){
        return User::findOrFail($this->attributes['created_by'])->name;
    }

    public function getFrontImage(){
        return ImageTool::resize($this->attributes['image'], 0, 0);
    }

    public function getBannerImage(){
        return ImageTool::resize($this->attributes['image_big'], 0, 0);
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ArticleValidation;
use App\Models\Article;
use App\Models\ImageTool;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ArticleController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $articles = Article::paginate($this->paginate);
        return view('admin.article.index',['articles'=>$articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $article = new Article();
        return view('admin.article.create',
            [
                'article' => $article,
                'locales' => $article->getLocale('create'),
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleValidation $request)
    {
        $article = Article::create($request->all());
        $article->available_translation = $request->all();
        foreach(config('translatable.locales') as $locale) {
            if($request->has('name-'.$locale) && !is_null($request->input('name-'.$locale))) {
                $article->translateOrNew($locale)->name = $request->input('name-'.$locale);
                $article->translate($locale)->description_short = $request->input('description_short-'.$locale);
                $article->translate($locale)->description = $request->input('description-'.$locale);
                $article->translate($locale)->meta_title = $request->input('meta_title-'.$locale);
                $article->translate($locale)->meta_description = $request->input('meta_description-'.$locale);
                $article->translate($locale)->meta_keyword = $request->input('meta_keyword-'.$locale);
            }
        }

        $article->save();

        return redirect()
            ->route('articles.index')
            ->with( 'message.level', 'success' )
            ->with( 'message.content', __('general.create_success') );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        $article['thumb'] = ImageTool::resize($article['image'],100,100);
        $article['thumb_big'] = ImageTool::resize($article['image_big'],100,100);

        return view('admin.article.edit',
            [
                'article' => $article,
                'locales' => $article->getLocale('edit'),
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleValidation $request, Article $article)
    {
        $article->update($request->all());
        if(! $request->has('published')) {
            $article->published = 0;
        }
        $article->available_translation = $request->all();
        foreach(config('translatable.locales') as $locale) {
            if($request->has('name-'.$locale) && !is_null($request->input('name-'.$locale))) {
                $article->translateOrNew($locale)->name = $request->input('name-'.$locale);
                $article->translate($locale)->description_short = $request->input('description_short-'.$locale);
                $article->translate($locale)->description = $request->input('description-'.$locale);
                $article->translate($locale)->meta_title = $request->input('meta_title-'.$locale);
                $article->translate($locale)->meta_description = $request->input('meta_description-'.$locale);
                $article->translate($locale)->meta_keyword = $request->input('meta_keyword-'.$locale);
            }
        }

        $article->save();

        return redirect()
            ->route('articles.index')
            ->with( 'message.level', 'success' )
            ->with( 'message.content', __('general.update_success') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()
            ->route('articles.index')
            ->with( 'message.level', 'success' )
            ->with( 'message.content', __('general.delete_success') );
    }
}

app/Http/Controllers/ArticleController.php
<?php
/**
 * Created by PhpStorm.
 * User: Aks13
 * Date: 09.01.2019
 * Time: 10:27
 */

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Support\Facades\App;
use App\Models\Feedback;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function index()
    {
        return view('article.list', [
            'articles'=>Article::where('published',1)->paginate(6)
        ]);
    }

    public function show(Request $request)
    {
        if($request->has('article')) {
            $article = Article::findOrFail($request->input('article'));
            return view('article.article', ['article'=>$article]);
        }
    }
}

resources/views/admin/article/create.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.articles'))
@section('content-title', __('general.articles'))

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> {{ __('general.dashboard') }}</a></li>
        <li><a href="{{ route('articles.index') }}"><i class="fa fa-newspaper-o"></i> {{ __('general.articles') }}</a></li>
        <li class="active"><i class="fa fa-newspaper-o"></i> {{ __('general.new') }}</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            {!! Form::open(['route' => 'articles.store','method' => 'post','files' => true]) !!}
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ __('general.article_creating') }}</h3>
                    <div class="pull-right">
                        {!! Form::submit(__('general.save'), ['class' => 'btn btn-success']) !!}

                        <a href="{{ route('articles.index') }}" class="btn btn-default"><i class="fa fa-share"></i></a>
                    </div>
                </div>
                <div class="box-body">

                    @include('admin.article.partials.form')

                    {!! Form::hidden('created_by', Auth::id()) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/article/edit.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.articles'))
@section('content-title', __('general.articles'))


@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> {{ __('general.dashboard') }}</a></li>
        <li><a href="{{ route('articles.index') }}"><i class="fa fa-newspaper-o"></i> {{ __('general.articles') }}</a></li>
        <li class="active"><i class="fa fa-newspaper-o"></i> {{ __('general.edit') }}</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            {!! Form::model($article, ['route' => ['articles.update', $article],'method' => 'put','files' => true]) !!}
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ __('general.article_edit') }}</h3>
                    <div class="pull-right">
                        {!! Form::submit(__('general.save'), ['class' => 'btn btn-success']) !!}

                        <a href="{{ route('articles.index') }}" class="btn btn-default"><i class="fa fa-share"></i></a>
                    </div>
                </div>
                <div class="box-body">
                    @include('admin.article.partials.form')
                    {!! Form::hidden('modified_by', Auth::id()) !!}
                </div>

            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/article/index.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.articles'))
@section('content-title', __('general.articles'))

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> {{ __('general.dashboard') }}</a></li>
        <li class="active"><i class="fa fa-newspaper-o"></i>{{ __('general.articles') }}</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ __('general.articles_list') }}</h3>
                    <div class="pull-right">
                        <a href="{{ route('articles.create') }}" class="btn btn-sm btn-success add_new_product">
                            {{ __('general.new') }}
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-hover table-striped table-bordered table-condensed">
                        <thead>
                        <tr>
                            <th>{{ __('general.slug') }}</th>
                            <th>{{ __('general.name') }}</th>
                            <th>{{ __('general.published') }}</th>
                            <th>{{ __('general.viewed') }}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($articles as $article)
                            <tr>
                                <td>{{ $article->slug }}</td>
                                <td>{{ $article->name }}</td>
                                <td>{{ $article->published }}</td>
                                <td>{{ $article->viewed }}</td>
                                <td class="td-action">
                                    <a class="btn btn-success btn-sm pull-left" href="{{ route('articles.edit', $article) }}">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <form onsubmit="if(confirm('{{ __('general.deleting') }}')){ return true }else{ return false }" action="{{ route('articles.destroy', $article) }}" method="post">
                                        <input type="hidden" name="_method" value="delete" />
                                        {{csrf_field()}}
                                        <button type="submit" class="btn-sm remove_item btn btn-danger pull-left"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td><h2>{{ __('general.empty_data') }}</h2></td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                    <nav aria-label="page navigation">
                        <ul class="pagination">
                            {{$articles->links()}}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
@endsection